# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first issue here! If you're reporting a ğŸ bug, please make sure you include steps to reproduce it.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ’– Thanks for opening your first pull request! ğŸ’–
  We use [semantic commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) to streamline the release process.
  Before your pull request can be merged, you should **make sure your first commit and PR title** start with a semantic prefix.
  This helps us to create release messages and credit you for your hard work!

  Examples of commit messages with semantic prefixes:
  
    - `fix: Fix LightGBM crashes with empty partitions`
    - `feat: Make HTTP on Spark back-offs configurable`
    - `docs: Update Spark Serving usage`
    - `build: Add codecov support`
    - `perf: improve LightGBM memory usage`
    - `refactor: make python code generation rely on classes`
    - `style: Remove nulls from CNTKModel`
    - `test: Add test coverage for CNTKModel`

  Make sure to check out the [developer guide](https://github.com/Microsoft/SynapseML/blob/master/CONTRIBUTING.md) for guidance on testing your change.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request, we appreciate your support! ğŸ‰ğŸ‰ğŸ‰
