name: synapseml
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.8
  - pyspark=3.1.2
  - requests
  - pip
  - r-base
  - r-dplyr
  - r-sparklyr=1.7.2
  - r-devtools=2.4.2
  - pip:
    - wheel
    - sphinx==4.2.0
    - sphinx_rtd_theme
    - coverage
    - pytest
    - pytest-cov
    - nbconvert
    - ipython
    - pytest-codeblocks
    - azure-storage-blob
    - twine
    - jupyter
    - mlflow
