name: synapseml
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11.8
  - requests=2.26.0
  - pip=25.2
  - r-base=4.1.1
  - r-sparklyr=1.8.1
  - r-devtools=2.4.2
  - cmake<=3.27
  - pip:
    - pyarrow==10.0.1
    - pyspark==3.5.0
    - pandas==2.0.3
    - wheel
    - sphinx==5.0.2
    - sphinx_paramlinks==0.5.2
    - sphinx_rtd_theme
    - coverage
    - pytest
    - pytest-cov
    - nbconvert
    - nbformat
    - pyyaml
    - PyGithub
    - tqdm
    - ipython
    - pytest-codeblocks
    - azure-storage-blob
    - jupyter
    - twine
    - mlflow
    - numpy
    - torch==2.1.0
    - torchvision==0.16.0
    # horovod package was deprecated in 2023, this commit has horovod compile with c++17
    # Ref: https://github.com/horovod/horovod/issues/3996#issuecomment-2098507345
    # Pre-built wheel for faster CI (built from same commit on Ubuntu 22.04 + Python 3.11)
    - https://mmlspark.blob.core.windows.net/installers/horovod-0.28.1-cp311-cp311-linux_x86_64.whl
    - petastorm>=0.11.0
    - pytorch_lightning==1.5.0
    - onnxmltools==1.7.0
    - matplotlib
    - Pillow
    - transformers==4.49.0
    - huggingface-hub==0.26.0
    - langchain==0.0.152
    - openai==0.27.5
    - black==22.3.0
    - black[jupyter]==22.3.0
    - mistletoe
    - markdownify
    - pypandoc
    - traitlets
    - opencv-python
    - sentence_transformers~=4.0.2
