name: synapseml
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.8
  - pyspark=3.1.2
  - requests
  - pip
  - r-base
  - r-dplyr
  - r-sparklyr
  - r-devtools
  - pip:
    - wheel
    - sphinx
    - sphinx_rtd_theme
    - coverage
    - pytest
    - pytest-cov
    - nbconvert
    - ipython
