name: synapseml
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.8
  - requests=2.26.0
  - pip=21.3
  - r-base=4.1.1
  - r-sparklyr=1.8.1
  - r-devtools=2.4.2
  - pip:
    - pyarrow>=0.15.0
    - pyspark==3.4.1
    - pandas==1.2.5
    - wheel
    - sphinx==4.2.0
    - sphinx_paramlinks==0.5.2
    - sphinx_rtd_theme
    - coverage
    - pytest
    - pytest-cov
    - nbconvert
    - nbformat
    - pyyaml
    - PyGithub
    - tqdm
    - ipython
    - pytest-codeblocks
    - azure-storage-blob
    - twine
    - jupyter
    - mlflow
    - numpy
    - torch==1.13.1
    - torchvision==0.14.1
    - horovod==0.28.1
    - petastorm>=0.11.0
    - pytorch_lightning==1.5.0
    - onnxmltools==1.7.0
    - matplotlib
    - Pillow
    - transformers==4.32.1
    - huggingface-hub>=0.8.1
    - langchain==0.0.151
    - openai==0.27.5
    - black==22.3.0
    - black[jupyter]==22.3.0
    - mistletoe
    - pypandoc
    - markdownify
    - traitlets
    - scikit-learn
    - opencv-python
