name: synapseml
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - requests=2.26.0
  - pip=21.3
  - r-base=4.1.1
  - r-sparklyr=1.8.1
  - r-devtools=2.4.2
  - pip:
    - azure-cli==2.60.0
    - azure-storage-blob==12.20.0
    - black[jupyter]==22.3.0
    - black==22.3.0
    - chardet==5.2.0
    - conda-pack==0.7.1
    - coverage==7.5.1
    - flake8==7.0.0
    - horovod==0.28.1
    - huggingface-hub==0.23.0
    - ipython==8.24.0
    - jupyter==1.0.0
    - langchain==0.0.152
    - markdownify==0.12.1
    - matplotlib==3.9.0
    - mistletoe==1.3.0
    - mlflow==2.12.2
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - numpy==1.26.4
    - onnxmltools==1.7.0
    - openai==0.27.5
    - opencv-python==4.9.0.80
    - pandas==1.5.0
    - petastorm==0.12.1
    - Pillow==10.3.0
    - pyarrow==15.0.2
    - PyGithub==1.59.1
    - pypandoc==1.13
    - pyspark==3.4.1
    - pytest-codeblocks==0.17.0
    - pytest-cov==5.0.0
    - pytest==8.2.0
    - pytorch_lightning==1.5.0
    - PyYAML==6.0.1
    - sphinx_paramlinks==0.5.2
    - sphinx_rtd_theme==2.0.0
    - sphinx==5.0.2
    - torch==2.0.0
    - torchvision==0.15.1
    - tqdm==4.66.4
    - traitlets==5.14.3
    - transformers==4.32.1
    - twine==5.0.0
    - wheel==0.43.0