name: synapseml
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.8
  - pyspark=3.1.3
  - requests=2.26.0
  - pip=21.3
  - r-base=4.1.1
  - r-sparklyr=1.7.6
  - r-devtools=2.4.2
  - pyarrow>=0.15.0
  - numpy>=1.19.3
  - pip:
    - pyspark==3.2.3
    - wheel
    - sphinx==4.2.0
    - sphinx_paramlinks==0.5.2
    - sphinx_rtd_theme
    - coverage
    - pytest
    - pytest-cov
    - nbconvert
    - ipython
    - pytest-codeblocks
    - azure-storage-blob
    - twine
    - jupyter
    - mlflow
    - torch==1.11.0
    - torchvision==0.12.0
    - horovod==0.25.0
    - petastorm>=0.11.0
    - pytorch_lightning==1.5.0
    - onnxmltools==1.7.0
    - matplotlib
    - Pillow
    - transformers==4.15.0
    - huggingface-hub>=0.8.1
