style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Microsoft/SynapseML
options:
  commit_groups:
    title_maps:
      build: Build ğŸ­
      chore: Maintenance ğŸ”§
      ci: Continuous Integration ğŸ’œ
      docs: Documentation ğŸ“˜
      feat: Features ğŸŒˆ
      fix: Bug Fixes ğŸ
      perf: Performance Improvements ğŸš€
      refactor: Code Refactoring ğŸ’
      revert: Revert Change â—€ï¸
      security: Security Fix ğŸ›¡ï¸
      style: Code Style ğŸ¶
      test: Testing ğŸ’š
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE