name: CI/Tests/R

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/*'
    - CODEOWNERS
    - .gitignore
    - README.md
    - CONTRIBUTING.md
    - '.github/**'
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-18.04
    timeout-minutes: 0
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.8.8
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: 3.8.8
        environment-file: environment.yml
        activate-environment: synapseml
    - name: Download Spark
      shell: bash -l {0}
      run: curl https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz -o spark-3.2.0-bin-hadoop3.2.tgz
    - name: Test R code
      shell: bash -l {0}
      run: |
        (timeout 5m sbt setup) || (echo "retrying" && timeout 5m sbt setup) || (echo "retrying" && timeout 5m sbt setup)
        (sbt coverage testR) || (echo "retrying" && sbt coverage testR) || (echo "retrying" && sbt coverage testR)
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/r-test-*.xml'
        check_name: "R Test Results"
        comment_title: "R Test Results"
    - name: Generate Codecov report
      if: always()
      shell: bash -l {0}
      run: sbt coverageReport
    - name: Get Codecov Secret from Key Vault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "mmlspark-keys"
        secrets: 'codecov-token'
      id: GetKeyVaultSecrets
    - name: Upload Coverage Report To Codecov.io
      if: always()
      shell: bash -l {0}
      run: |
        set -e
        curl -s https://codecov.io/bash > .codecov
        chmod +x .codecov
        echo "Starting Codecov Upload"
        ./.codecov -t ${{ steps.GetKeyVaultSecrets.outputs.codecov-token }}
