on: [pull_request]

jobs:
  add_pr_comment:
    runs-on: ubuntu-latest
    name: Azure OpenAI PR Comment
    steps:
      - id: review
        uses: microsoft/gpt-review@v0.9.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_API: ${{ secrets.AZURE_OPENAI_API }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
